version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy-voltbras
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  node:
    image: node:13.10.1-alpine3.10
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: |
      sh -c "
        yarn
        cp .env.example .env
        yarn start
      "
    expose:
      - 3000
    depends_on:
      - database
    environment:
      - VIRTUAL_HOST=voltbras-challenge.localhost
      - VIRTUAL_PORT=8081

  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=exoplanets
    volumes:
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb-volume:/data/db
    ports:
      - 28017
      - 27017
